assignment/assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('endpoints.urls'))
]

assignment/endpoints/urls.py
from django.urls import path
from . import views

app_name = 'endpoints'
urlpatterns = [
    path('', views.index, name='index'),
    path('view-1/', views.view_1, name='view_1'),
    path('view-2/', views.view_2, name='view_2')
]

assignment/endpoints/models.py
from django.db import models

# Create your models here.

assignment/endpoints/views.py
# SWDV 620: Web Applications
# Django views

from django.shortcuts import render

def index(request):
    return render(request, 'endpoints/index.html')

def view_1(request):
    return render(request, 'endpoints/view_1.html')

def view_2(request):
    context = {'message': 'Hello from the view_2 function!'}
    return render(request, 'endpoints/view_2.html', context)

assignment/endpoints/templates/endpoints/index.html
<!DOCTYPE html>

<html lang="en-US">
    <!-- SWDV 620: Web Applications -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Index</title>
    </head>

    <body>
        <nav>
            <a href="{% url 'endpoints:view_1' %}">View 1</a>
            <a href="{% url 'endpoints:view_2' %}">View 2</a>
        </nav>

        <h1>Home Page</h1>
    </body>
</html>

assignment/endpoints/templates/endpoints/view_1.html
<!DOCTYPE html>

<html lang="en-US">
    <!-- SWDV 620: Web Applications -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>View 1</title>
    </head>

    <body>
        <nav>
            <a href="{% url 'endpoints:index' %}">Home</a>
            <a href="{% url 'endpoints:view_2' %}">View 2</a>
        </nav>
        
        <h1>This is view 1!</h1>
    </body>
</html>

assignment/endpoints/templates/endpoints/view_2.html
<!DOCTYPE html>

<html lang="en-US">
    <!-- SWDV 620: Web Applications -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>View 2</title>
    </head>

    <body>
        <nav>
            <a href="{% url 'endpoints:index' %}">Home</a>
            <a href="{% url 'endpoints:view_1' %}">View 1</a>
        </nav>
        
        <h1>This is view 2!</h1>
        <p>{{ message }}</p>
    </body>
</html>